const express = require('express')
const router = express.Router()
const siteController =require('../app/controllers/SiteController')
const loginController =require('../app/controllers/LoginController')
const usersController =require('../app/controllers/UsersController')
const courseController =require('../app/controllers/CourseController')
const middleware = require('../utils/middleware')
router.get('/register',usersController.register)
router.post('/register',usersController.checkUser,usersController.checkUser1)
router.get('/login',loginController.index)
router.post('/login',loginController.index1)
router.get('/logout',loginController.logout)
router.get('/showall/:page',courseController.showAll)
router.get('/search/:page',siteController.search)
router.get('/showall',courseController.showAll)
router.get('/search',siteController.search)
router.get('/:slug',middleware.loginNext,courseController.findUserCreate,courseController.showComment,courseController.show)

router.get('/',siteController.index)
module.exports =router